baseURL: "https://examplesite.com/"
title: XSCAPE's Blog
paginate: 5
theme: PaperMod
defaultContentLanguage: zh

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: XSCAPE's Blog
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: xscape_dev
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006/01/02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "XSCAPE's Blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: XSCAPE's Blog
    subtitle: "No love, No idea"
    imageUrl: "https://pic1.zhimg.com/v2-a461f086cf0c0e4c212a37929005a459_xl.jpg?source=fdaf910d"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar
    buttons:
      - name: 文章
        url: posts
      - name: 标签
        url: tags
      - name: 摄影

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "\U0001F4BB 后端研发工程师，C#、Golang、C、微服务、服务治理"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: "\u2728 Categories"
      url: /categories/
      weight: 10
    - identifier: tags
      name: "\u270D Tags"
      url: /tags/
      weight: 20
    - identifier: example
      name: "\u26A1 Links"
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai
